image: kaminchu/tftp

# プロジェクトのsecret-variablesで設定すべし
# https://docs.gitlab.com/ee/ci/variables/#secret-variables
variables:
#  TARGET_IP: "192.168.0.254"
#  ADMIN_PASS: "adminpass"
#  CONFIG_NO: "0"

stages:
  - deploy

deploy:
  stage: deploy
  when: manual
  only:
    - main
  script:
    - "tftp ${TARGET_IP} put ${CONFIG_FILE} config${CONFIG_NO}/${ADMIN_PASS}"